### ISSUE TITLE
No SEE ALSO section

### ISSUE THREAD

**Issue by karenetheridge** [alnewkirk/API-Facebook#1]
There are a bunch of other Facebook API distributions on the CPAN -- what makes this one better?

**Comment by alnewkirk** [comment]
"Better" is both a relative and subjective term. This distribution is simply different. It only promises to provide a thin-client interface which makes it fully future-proof; It has a lean dependency chain (provided you're using Perl 5.14+); and the API is consistent with others in its family of web-service client libraries.

**Comment by karenetheridge** [comment]
Well, to rephrase -- if I'm doing some integration with Facebook, when/why might I want to choose this distribution over others?

**Comment by alnewkirk** [comment]
If you desire to make asynchronous HTTP requests; or if you're using Mojo/Mojolicious (or derived frameworks) to write non-blocking apps that make HTTP requests, this distribution would make that easier. If you want a consistent OO experience across all FB Graph APIs (ad, social, events, analytics, etc), then this distribution would provide that. Additionally, the client has retry logic (protects against intermittent FB failures), and, it's easy to log/debug (just enable debugging and pipe/watch STDOUT).
